name: Go fuzz test

on:
  push:
  pull_request:
  
jobs:
  fuzz-test:
    name: Fuzz test
    runs-on: ubuntu-latest
    steps:
      - name: Go fuzz test
        uses: jidicula/go-fuzz-action@v1.2.0

        with:
          fuzz-time: 30s
          fuzz-minimize-time: 1m
          fuzz-regexp: OtherFuzzRegexp
